type Source = { id: string; name: string; thumbnail: string };
type HostApi = { listSources: () => Promise<Source[]>; openExternal: (url: string) => Promise<void>; publicUrl: () => Promise<string> };
declare global { interface Window { screenShare: HostApi } }
export {};
type Quality = { width: number; height: number; frameRate: number };

const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;
const preview = $('preview') as HTMLVideoElement;
const sourceLabel = $('sourceLabel'); const picker = $('sourcePicker'); const sources = $('sources');
const message = $('message'); const roomCode = $('roomCode'); const connectionStatus = $('connectionStatus'); const viewerCount = $('viewerCount');
const audioStatus = $('audioStatus'); const screenStatus = $('screenStatus'); const startButton = $('start') as HTMLButtonElement; const stopButton = $('stop') as HTMLButtonElement;
let selected: Source | undefined; let stream: MediaStream | undefined; let socket: WebSocket; let publicUrl = ''; let code = ''; let roomToken = ''; let reconnectTimer: ReturnType<typeof setTimeout> | undefined; const peers = new Map<string, RTCPeerConnection>();
const qualities: Record<string, Quality> = { '720p30': { width: 1280, height: 720, frameRate: 30 }, '1080p30': { width: 1920, height: 1080, frameRate: 30 }, '1080p60': { width: 1920, height: 1080, frameRate: 60 } };
function notify(text: string) { message.textContent = text; }
function send(value: unknown) { if (socket?.readyState === WebSocket.OPEN) socket.send(JSON.stringify(value)); }
$('selectSource').addEventListener('click', async () => { sources.innerHTML = ''; for (const source of await window.screenShare.listSources()) { const button = document.createElement('button'); button.className = 'source'; button.innerHTML = `<img src="${source.thumbnail}" alt=""><span>${source.name}</span>`; button.onclick = async () => { selected = source; sourceLabel.textContent = source.name; picker.classList.add('hidden'); await refreshCapture(); }; sources.appendChild(button); } picker.classList.remove('hidden'); });
$('closePicker').addEventListener('click', () => picker.classList.add('hidden'));
$('netflix').addEventListener('click', () => window.screenShare.openExternal('https://www.netflix.com/'));
$('createRoom').addEventListener('click', async () => { if (!selected) return notify('Selecione uma tela ou janela antes de criar a sala.'); publicUrl = await window.screenShare.publicUrl(); connectHost(false); });
$('start').addEventListener('click', async () => { if (!selected || !code) return; if (await refreshCapture()) { startButton.disabled = true; stopButton.disabled = false; send({ type: 'start' }); } });
$('quality').addEventListener('change', () => { void refreshCapture(); });
$('audioMode').addEventListener('change', () => { void refreshCapture(); });
$('stop').addEventListener('click', () => { stream?.getTracks().forEach((track) => track.stop()); stream = undefined; preview.srcObject = null; peers.forEach((peer) => peer.close()); peers.clear(); send({ type: 'stop' }); screenStatus.textContent = 'PARADA'; audioStatus.textContent = 'DESATIVADO'; startButton.disabled = false; stopButton.disabled = true; });
$('copyCode').addEventListener('click', () => navigator.clipboard.writeText(code)); $('copyLink').addEventListener('click', () => navigator.clipboard.writeText(`${publicUrl}/watch/${code}`));
async function captureSelectedSource() { if (!selected) return undefined; const quality = qualities[($('quality') as HTMLSelectElement).value]; const mode = ($('audioMode') as HTMLSelectElement).value; const audio = mode !== 'none' ? ({ mandatory: { chromeMediaSource: 'desktop', chromeMediaSourceId: selected.id } } as MediaTrackConstraints) : false; const video = { mandatory: { chromeMediaSource: 'desktop', chromeMediaSourceId: selected.id, minWidth: quality.width, maxWidth: quality.width, minHeight: quality.height, maxHeight: quality.height, maxFrameRate: quality.frameRate } } as MediaTrackConstraints; return navigator.mediaDevices.getUserMedia({ audio, video }); }
async function refreshCapture() { if (!selected || (!stream && !code)) return false; try { const nextStream = await captureSelectedSource(); if (!nextStream) return false; const previousStream = stream; const nextVideo = nextStream.getVideoTracks()[0] || null; const nextAudio = nextStream.getAudioTracks()[0] || null; peers.forEach((peer) => { const videoSender = peer.getSenders().find((sender) => sender.track?.kind === 'video'); const audioSender = peer.getSenders().find((sender) => sender.track?.kind === 'audio'); if (videoSender) void videoSender.replaceTrack(nextVideo); if (audioSender) void audioSender.replaceTrack(nextAudio); }); stream = nextStream; preview.srcObject = nextStream; previousStream?.getTracks().forEach((track) => track.stop()); screenStatus.textContent = 'TRANSMITINDO'; audioStatus.textContent = nextAudio ? 'TRANSMITINDO' : 'DESATIVADO'; if (previousStream) notify('Transmissão atualizada sem criar outra sala.'); return true; } catch { notify('Não foi possível aplicar esta alteração. Conteúdo protegido pode aparecer preto pelo sistema ou provedor.'); return false; } }
function connectHost(resume: boolean) { const url = new URL(publicUrl); url.protocol = url.protocol === 'https:' ? 'wss:' : 'ws:'; socket = new WebSocket(url.toString()); socket.onopen = () => send(resume ? { type: 'resume-room', code, token: roomToken } : { type: 'create-room' }); socket.onclose = () => { connectionStatus.textContent = 'RECONECTANDO'; connectionStatus.className = ''; if (code && roomToken) reconnectTimer = setTimeout(() => connectHost(true), 1000); }; socket.onerror = () => notify('Conexão com o servidor público instável. Tentando reconectar...'); socket.onmessage = async (event) => handle(JSON.parse(event.data)); }
async function handle(msg: any) { if (msg.type === 'room-created') { code = msg.code; roomToken = msg.token; roomCode.textContent = code; connectionStatus.textContent = 'CONECTADO'; connectionStatus.className = 'ok'; $('copyCode').removeAttribute('disabled'); $('copyLink').removeAttribute('disabled'); startButton.disabled = false; $('createRoom').setAttribute('disabled', 'true'); notify(`Compartilhe ${publicUrl}/watch/${code}`); } if (msg.type === 'room-resumed') { connectionStatus.textContent = 'CONECTADO'; connectionStatus.className = 'ok'; notify(`Sala reconectada: ${publicUrl}/watch/${code}`); } if (msg.type === 'viewer-joined') { viewerCount.textContent = String(Number(viewerCount.textContent) + 1); await createPeer(msg.viewerId, msg.iceServers); } if (msg.type === 'answer') { const peer = peers.get(msg.viewerId) || [...peers.values()][0]; if (peer) await peer.setRemoteDescription(msg.description); } if (msg.type === 'ice') { const peer = peers.get(msg.viewerId) || [...peers.values()][0]; if (peer && msg.candidate) await peer.addIceCandidate(msg.candidate); } if (msg.type === 'viewer-left') viewerCount.textContent = String(msg.count); }
async function createPeer(viewerId: string, iceServers: RTCIceServer[]) { if (!stream) return; const peer = new RTCPeerConnection({ iceServers }); peers.set(viewerId, peer); stream.getTracks().forEach((track) => peer.addTrack(track, stream!)); peer.onicecandidate = (event) => event.candidate && send({ type: 'ice', viewerId, candidate: event.candidate }); peer.onconnectionstatechange = () => { if (peer.connectionState === 'failed') { notify('Falha ICE. Verifique a configuração TURN do servidor.'); peer.restartIce(); } }; const offer = await peer.createOffer(); await peer.setLocalDescription(offer); send({ type: 'offer', viewerId, description: peer.localDescription }); }
